services:
  ffl-testing-renderer:
    build:
      context: .
      dockerfile: Dockerfile.ffl-testing-renderer
    container_name: ffl-testing-renderer
    expose:
      - "12346"
    devices:
      - /dev/dri:/dev/dri

  ffl-testing-web-server:
    build:
      context: .
      dockerfile: Dockerfile.ffl-testing-web-server
    container_name: ffl-testing-web-server
    ports:
      - "5000:5000"
    depends_on:
      - ffl-testing-renderer
